### ISSUE TITLE
RB properties

### ISSUE THREAD

**Issue by Maeeen** [PedroChaps/2024-EPFL-DA-Exam-Anki#1]
![image](https://github.com/PedroChaps/2024-EPFL-DA-Exam-Anki/assets/32419465/6f5d9588-fa58-46dc-8bd3-e1d29f56ddd5)

Isn't RB4 missing the (L) ?

**Comment by PedroChaps** [comment]
Yeah, I think I am missing in some and eventually just stopped putting the type of property in the questions 😅

Will add that to the queue of changes

**Comment by Maeeen** [comment]
I do not think that an .apkg file can be properly tracked for changes on Git; so I can not make any PR :/

**Comment by PedroChaps** [comment]
Oh, no worries, I'll take care of it once I get back to studying

**Comment by PedroChaps** [comment]
@Maeeen fixed! :D
